[book]
title = "Ballerina Security"
authors = ["Chanaka Lakmal"]
language = "en"
multilingual = false
src = "src"
description = "The examples, use-cases, demonstrations, and resources related to microservices security patterns with Ballerina, which is an open-source programming language for the cloud that makes it easier to use, combine, and create network services."

[output.html]
theme = "theme"
default-theme = "light"
git-repository-url = "https://github.com/ldclakmal/ballerina-security"
site-url = "/ballerina-security/"

[output.html.fold]
enable = true

[output.html.print]
enable = false
